### ISSUE TITLE
Data format changed?

### ISSUE THREAD

**Issue by spib** [logzio/logzio-dotnet#20]
Hi,

We just upgraded the lo4net appender from version 0.20.0 to the latest 1.0.1, and we've noticed that the data is now being shipped in a 'logData'

Here's an example posted from v0.20

![image](https://user-images.githubusercontent.com/512036/44579209-95305480-a78d-11e8-8386-99a8a5c5857e.png)

And then an example from v1.0.1

![image](https://user-images.githubusercontent.com/512036/44579280-c446c600-a78d-11e8-8c4e-a3ea7d076661.png)

Was this an intentional change? Seems like a step backwards?

**Comment by snakefoot** [comment]
Think the change was made to allow support for any number of parameters:

See also:
https://logging.apache.org/log4net/release/sdk/html/P_log4net_Core_LoggingEvent_Properties.htm

One could argue that mandatory parameters like "timestamp" + "mesage" + "level" + "logger" could be included in the primary scope, instead of in the LogData-collection (of random properties). But maybe a developer at Logzio have a better explanation.

**Comment by idohalevi** [comment]
@spib 
I feel like you are correct,`message` and `timestamp` should be in the primary scope, I will take a look to see what cause this change

**Comment by snakefoot** [comment]
@idohalevi Sorry about this. Believe it is my fault. I have now created  #23 to fix this
