### ISSUE TITLE
does not read the variables in the config

### ISSUE THREAD

**Issue by rgarofalo** [logzio/logzio-dotnet#22]
with nlog the variables in the config are not used to generate the log

**Comment by snakefoot** [comment]
@rgarofalo What properties are important for you to configure with layout-variables?

**Comment by rgarofalo** [comment]
I noticed this behavior with an application developed with the 0.20 version and then updated to the latest version, the variables are not reported in the log

**Comment by snakefoot** [comment]
@rgarofalo Ahh thought you meant configure the target options using NLog varables.

Yes the target no longer includes all NLog variables in its output, because NLog variables are often used for other targets and not always related to a specific target.

Instead you have to explicitly specify what NLog variables that should be included in output using `contextproperty` (Can also include other things like `${threadid}`, `${machinename}`, etc.):

https://github.com/logzio/logzio-dotnet/blob/master/docs/nlog.md#context-properties

**Comment by idohalevi** [comment]
@rgarofalo 
Did @snakefoot answer helped with what you need?

**Comment by rgarofalo** [comment]
it was helpful, thank you very much
